Typeidea_s/Typeidea_s/urls.py
#coding=utf-8
"""Typeidea_s URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

from blog.views import IndexView,CategoryView,TagView,PostDetailView,SearchView,AuthorView
from blog.apis import PostViewSet,CategoryViewSet
from config.views import LinkListView
from comment.views import CommentView

from .autocomplete import CategoryAutocomplete,TagAutocomplete

import xadmin

from config.views import links
from .custom_site import custom_site

'''
P142
url的定义理解为一个路径（正则字符串）对一个函数的映射
url(<正则字符串>,<view function>, <固定参数contentxt>, <url的名称>)

?P<value>:就是命名一个名字为value的组，匹配规则符合后面的/d+


funtionView URL的写法

urlpatterns = [
    url(r'^$', post_list),
    url(r'^category/(?P<category_id>\d+)/$', post_list, name= 'category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', post_list, name= 'tag-list'),
    url(r'^post/(?P<post_id>\d+).html$', post_detail, name= 'post-detail'),
    url(r'^links/$', links, name= 'links'),

    url(r'^super_admin/', admin.site.urls, name= 'super-admin'),
    url(r'^admin/', custom_site.urls, name= 'admin')
]
'''

router = DefaultRouter()
router.register(r'post', PostViewSet, base_name='api-post')
router.register(r'category',CategoryViewSet, base_name='api-category')

# class-based view URL写法
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name= 'category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view() , name= 'tag-list'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name= 'post-detail'),
    url(r'^links/$', LinkListView.as_view(), name= 'links'),
    url(r'^search/$',SearchView.as_view(), name = 'search'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name = 'author'),
    url(r'^comment/$',CommentView.as_view(), name='comment'),
    url(r'^super_admin/', admin.site.urls, name= 'super-admin'),
    url(r'^admin/', xadmin.site.urls, name= 'xadmin'),
    url(r'^category-autocomplete/$', CategoryAutocomplete.as_view(),name ='category-autocomplete' ),
    url(r'^tag-autocomplete/$', TagAutocomplete.as_view(), name = 'tag-autocomplete'),
    url(r'^ckeditor/',include('ckeditor_uploader.urls')),
    #url(r'^api/post/',post_list,name='post-list'),
    #url(r'^api/post/', PostList.as_view(), name='post-list'),
    url(r'^api/',include(router.urls, namespace='api')),
    url(r'^api/docs/', include_docs_urls(title='Typeidea_s apis')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
'''
ckeditor_uploader.urls:提供了接受上传图片和浏览已上传图片接口
后面增加的static用来配置图片资源访问，可以理解为Django内置的静态文件处理功能提供静态文件服务
'''

Typeidea_s/comment/models.py
#coding=utf-8
from django.db import models
from blog.models import Post

# Create your models here.
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = "评论"

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

Typeidea_s/comment/forms.py
#__author__ = 'lenovo'
#coding=utf-8
from django import forms
from .models import Comment
import mistune

class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label = '昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs = {'class':'form-control','style':"width:60%;"}
        )
    )

    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class':'form-control','style':"width:60%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class':'form-control','style':"width:60%;"}
        )
    )

    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows':6,'cols':60,'class':'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content)<10:
            raise forms.ValidationError('内容长度怎么能这么短呢！')
        content = mistune.markdown(content)
        return content
    class Meta:
        model = Comment
        fields = ['nickname','email','website','content']

Typeidea_s/Typeidea_s/themes/default/templates/comment/block.html
<hr/>
<div class="comment">
    <form class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <input type="submit" value="写好了！">
    </form>
    <!-- 评论列表-->
    <ur class="list-group">
        {% for comment in comment_list %}
            <li class="list-group-item">
                <div class="nickname">
                    <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                    <span>{{ comment.created_time }}</span>
                </div>
                <div class="comment-content">
                    {% autoescape off %}
                    {{ comment.content }}
                    {% endautoescape %}
                </div>
            </li>
        {% endfor %}
    </ur>
</div>

Typeidea_s/Typeidea_s/themes/default/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {TEXT-ALIGN: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
    <div class="result">
        {% if succeed %}
            评论成功！
            <a href="{{ target }}">返回</a>
        {% else %}
            <ur class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ur>
            <a href="javascript:window.history.back();">返回</a>
        {% endif%}
    </div>
</body>
</html>